Repository spryker/silexphp, pull requests merged in 2019-01, with the labels that each got.

#4 TE-1065: Updated symfony/twig-bridge composer constraints. Fixed tests.
  composer.json
  tests/Silex/Tests/Provider/TwigServiceProviderTest.php
Labels: bug, ready-for-release

#8 TE 1359 removed deprecation warnings which were added to early.
  src/Silex/Provider/ServiceControllerServiceProvider.php
  src/Silex/Provider/TwigServiceProvider.php
  src/Silex/ServiceProviderInterface.php
Labels: ready-for-release

#5 TE-648: Enabling step 3
  composer.json
  src/Silex/Application.php
  tests/Silex/Tests/Application/SecurityTraitTest.php
  tests/Silex/Tests/ApplicationTest.php
  tests/Silex/Tests/ExceptionHandlerTest.php
  tests/Silex/Tests/FunctionalTest.php
  tests/Silex/Tests/LazyDispatcherTest.php
  tests/Silex/Tests/LocaleTest.php
  tests/Silex/Tests/MiddlewareTest.php
  tests/Silex/Tests/Provider/HttpCacheServiceProviderTest.php
  tests/Silex/Tests/Provider/HttpFragmentServiceProviderTest.php
  tests/Silex/Tests/Provider/MonologServiceProviderTest.php
  tests/Silex/Tests/Provider/RememberMeServiceProviderTest.php
  tests/Silex/Tests/Provider/SecurityServiceProviderTest.php
  tests/Silex/Tests/Provider/SessionServiceProviderTest.php
  tests/Silex/Tests/Provider/SwiftmailerServiceProviderTest.php
  tests/Silex/Tests/Provider/TwigServiceProviderTest.php
  tests/Silex/Tests/Provider/UrlGeneratorServiceProviderTest.php
  tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php
  tests/Silex/Tests/Route/SecurityTraitTest.php
  tests/Silex/Tests/RouterTest.php
  tests/Silex/Tests/ServiceControllerResolverRouterTest.php
Labels: improvement, ready-for-release
